# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem 'colorize'
group :development do
  gem 'pry-byebug'
  gem 'rubocop'
  gem 'solargraph'
end
