# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'pry'
  gem 'puma'
  gem 'rack'
  gem 'rubocop'
end
