# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem 'i18n'
gem 'russian', '~> 0.6.0'
gem 'state_machines'
group :development do
  gem 'pry-byebug'
  gem 'rubocop'
  gem 'solargraph'
end
